{
 "title": "Ethereum Validator Watcher OSS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ethereum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kiln future blocks proposal",
   "type": "stat",
   "description": "In next two epochs",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(future_block_proposals_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kiln assets under management",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * $B * 32", "type": "math" }
   ]
  },
  {
   "title": "Total staking market cap",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*$B*32", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 1 },
   "options": {
    "content": "<div style=\"width:100%;height:100%;display:flex;flex-direction:row;align-items:center;justify-content:center\">\n<img src=\"https://ethereum.org/static/eth-diamond-rainbow.svg\" height=\"100%\" width=\"100%\" style=\"max-width:100%;max-height:100%\"/>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": {
    "content": "<div style=\"width:100%;height:100%;display:flex;flex-direction:row;align-items:center;justify-content:center\">\n<img src=\"https://user-images.githubusercontent.com/79211569/170065083-5deff6bf-a786-4550-93f2-dd4eb5ae1f9f.svg\" height=\"100%\" width=\"100%\" style=\"max-width:100%;max-height:100%;\"/>\n</div>"
   }
  },
  {
   "title": "Kiln slashed validators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(our_slashed_validators_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network slashed validators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(total_slashed_validators_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Ethereum epoch",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(epoch)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "description": "Ethereum slot",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(slot)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kiln queued validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(our_pending_queued_validators_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network queued validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(total_pending_queued_validators_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kiln's share of validators in entry queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100*$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Entry queue duration estimation",
   "type": "stat",
   "description": "Average between Minimum and Maximum entry queue time.\nhttps://docs.google.com/spreadsheets/d/1gufxMdWPLgKl-qRsSfAhvvBOra0BsQmeukcWJY9Fsi8/edit#gid=600135599",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(entry_queue_duration_sec)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ETH price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(eth_usd)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kiln exited validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(our_exited_validators_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch completion",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(slot) % 32", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kiln active validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(our_active_validators_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network active validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(total_active_validators_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kiln's share of active validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100*$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Kiln ideal att. rewards (24H)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A+$B+$C)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Kiln actual att. rewards (24H)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A-$B+$C-$D+$E)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Kiln att. rewards shortfall & penalties (24H)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($J-$I)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Kiln att. rewards rate (24H)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$J/$I", "type": "math" }
   ]
  },
  {
   "title": "Network ideal att. rewards (24H)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A+$B+$C)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Network actual att. rewards (24H)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A-$B+$C-$D+$E)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Network att. rewards shortfall & penalties (24H)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($J-$I)/10**9", "type": "math" }
   ]
  },
  {
   "title": "Network att. rewards rate (24H)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$J/$I", "type": "math" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{app=\"ethereum-validator-watcher\"}"
    }
   ]
  },
  {
   "title": "Kiln Suboptimal attestations rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(suboptimal_attestations_rate)",
     "legendFormat": "Raw"
    },
    {
     "expr": "max(min_over_time(suboptimal_attestations_rate[2m]))",
     "legendFormat": "1 min - mini value "
    }
   ]
  },
  {
   "title": "Blocks built with non-allowlisted relay (24H)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "max(round(increase(bad_relay_count_total[24h]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kiln missed block proposals in the last 24H",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "max(increase(missed_block_proposals_head_count_total[24h]))",
     "legendFormat": "Head"
    },
    {
     "expr": "max(increase(missed_block_proposals_finalized_count_total[24h]))",
     "legendFormat": "Finalized"
    }
   ]
  },
  {
   "title": "Untimely or bad target vote",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(net_suboptimal_targets_rate)",
     "legendFormat": "Network"
    },
    {
     "expr": "max(our_suboptimal_targets_rate)",
     "legendFormat": "Us"
    }
   ]
  },
  {
   "title": "Kiln missed attestations during the last epoch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "targets": [
    { "expr": "max(missed_attestations_count)", "legendFormat": "Simple" },
    {
     "expr": "max(double_missed_attestations_count)",
     "legendFormat": "Double"
    }
   ]
  },
  {
   "title": "Untimely or bad head vote",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "max(net_suboptimal_heads_rate)", "legendFormat": "Network" },
    { "expr": "max(our_suboptimal_heads_rate)", "legendFormat": "Us" }
   ]
  },
  {
   "title": "Untimely or bad source vote",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(net_suboptimal_sources_rate)",
     "legendFormat": "Network"
    },
    {
     "expr": "max(our_suboptimal_sources_rate)",
     "legendFormat": "Us"
    }
   ]
  }
 ]
}