{
 "title": "Ethereum Kiln Breakdown",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "12s",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(eth_future_block_proposals,network)"
    }
   },
   {
    "name": "breakdown",
    "query": {
     "query": "label_values(eth_validator_status_count,scope)"
    }
   }
  ]
 },
 "panels": [
  { "title": "🖧 Network 🖧", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quick Links",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "\n- [open an issue](https://github.com/kilnfi/eth-validator-watcher/issues/new)\n- [github repository](https://github.com/kilnfi/eth-validator-watcher)\n- [beaconcha.in](https://beaconcha.in/)\n- [bageth.xyz](https://www.bageth.xyz/)\n- [etherscan.io](https://etherscan.io/)"
   }
  },
  {
   "title": "Number of validators",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (scope) (eth_validator_status_count{status=~\"active_ongoing|active_exiting\", scope!=\"scope:all-network\", scope=~\"${breakdown}.*\", network=\"${network}\"})",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Future Block Proposals",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (scope) (eth_future_block_proposals{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"})",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Effectiveness",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (scope) (avg_over_time(eth_consensus_rewards_rate{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[$__interval]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  { "title": "🧱 Block Proposals 🧱", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Missed blocks last 24H",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by (scope) (increase(eth_missed_block_proposals_finalized_total{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[24h]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Block Proposals",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(max (increase(eth_block_proposals_finalized_total{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[5m]) != 0) by (scope))\n\nor\n\n(min (increase(eth_missed_block_proposals_finalized_total{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[5m])) by (scope) * 1000)",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  { "title": "✍ Attestations ✍", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Missed Attestations Per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max by (scope) (eth_missed_attestations{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"})",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Consecutive Missed Attestations Per Epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "max by (scope) (eth_missed_consecutive_attestations{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"})",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  { "title": "🎯 Accuracy 🎯", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Source Vote",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - avg by (scope) (avg_over_time(eth_suboptimal_sources_rate{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[$__interval]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Target Vote",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - avg by (scope) (avg_over_time(eth_suboptimal_targets_rate{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[$__interval]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Head Vote",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - avg by (scope) (avg_over_time(eth_suboptimal_heads_rate{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[$__interval]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Source Vote 24h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "100.0 - avg by (scope) (avg_over_time(eth_suboptimal_sources_rate{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[24h]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Target Vote 24h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "100.0 - avg by (scope) (avg_over_time(eth_suboptimal_targets_rate{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[24h]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  },
  {
   "title": "Head Vote 24h",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "100.0 - avg by (scope) (avg_over_time(eth_suboptimal_heads_rate{scope=~\"${breakdown}:.*\", scope!=\"scope:all-network\", network=\"${network}\"}[24h]))",
     "legendFormat": "{{ scope }}"
    }
   ]
  }
 ]
}