apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethereum-validator-watcher.fullname" . }}-config
  labels:
    {{- include "ethereum-validator-watcher.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ .Values.config | nindent 4 }}
