{{- if .Values.config.watchedKeys }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethereum-validator-watcher.fullname" . }}
  labels:
    {{- include "ethereum-validator-watcher.labels" . | nindent 4 }}
data:
  watched-keys.txt: |
  {{- range .Values.config.watchedKeys }}
  {{- . | nindent 4 }}
  {{- end }}
{{- end }}
