apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ethereum-validator-watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ethereum-validator-watcher.labels" . | nindent 4 }}
  {{- with .Values.watcher.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.watcher.replicaCount }}
  selector:
    matchLabels:
      {{- include "ethereum-validator-watcher.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ethereum-validator-watcher.matchLabels" . | nindent 8 }}
        {{- with .Values.watcher.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.watcher.podAnnotations }}
      annotations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: validator-watcher
        image: "{{ .Values.watcher.image.repository }}:{{ .Values.watcher.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.watcher.image.pullPolicy }}
        {{- with .Values.watcher.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8000
        args:
          {{- if .Values.watcher.config.watchedKeys }}
          - --pubkeys-file-path=/data/keys/watched-keys.txt
          {{- end }}
          - --beacon-url={{ .Values.watcher.config.beaconUrl }}
          - --beacon-type={{ .Values.watcher.config.beaconType }}
          - --liveness-file=/tmp/liveness
          {{- with .Values.watcher.extraArgs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.watcher.livenessProbe }}
        livenessProbe:
          exec:
            command:
            - /usr/bin/python3.9
            - /usr/local/bin/liveness_check.py
            - /tmp/liveness
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        {{- with .Values.watcher.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - /usr/bin/python3.9
            - /usr/local/bin/liveness_check.py
            - /tmp/liveness
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
        {{- end }}
        volumeMounts:
        {{- if .Values.watcher.config.watchedKeys }}
          - name: "watched-keys"
            mountPath: "/data/keys"
            readOnly: true
         {{- end }}
        {{- with .Values.watcher.volumeMounts }}
          {{- toYaml . | nindent 12 }}
        {{- end }}
      serviceAccountName: {{ include "ethereum-validator-watcher.serviceAccountName" . }}
      volumes:
      {{- if .Values.watcher.config.watchedKeys }}
        - name: "watched-keys"
          configMap:
              name: {{ include "ethereum-validator-watcher.fullname" . }}
      {{- end }}
      {{- with .Values.watcher.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
