apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ethereum-validator-watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ethereum-validator-watcher.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ethereum-validator-watcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ethereum-validator-watcher.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml")  . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: validator-watcher
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8000
        {{- with .Values.env }}
        env:
        {{- range $name, $value := . }}
        {{- $type := typeOf $value }}
          - name: {{ $name }}
        {{- if eq $type "string" }}
            value: {{ $value | quote }}
        {{- else }}
          {{- toYaml $value | nindent 12 }}
        {{- end }}
        {{- end }}
        {{- end }}
        args:
          - --config=/config/config.yaml
          {{- range $key, $value := .Values.extraArgs }}
          {{- if eq ($value | quote | len) 2 }}
          - --{{ $key }}
          {{- else }}
          - --{{ $key }}={{ $value }}
          {{- end }}
          {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /config
      serviceAccountName: {{ include "ethereum-validator-watcher.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "ethereum-validator-watcher.fullname" . }}-config
