name: charts::ghcr-oci

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/workflows/helm-chart.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/workflows/helm-chart.yaml"

permissions:
  id-token: write
  actions: write
  pull-requests: write
  issues: write
  contents: write
  packages: write

jobs:
  helm-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main --chart-dirs charts)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main --chart-dirs charts

  helm-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - helm-lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.0

      - name: 'helm:package:create'
        run: |
          helm package charts/

      - name: 'helm:package:get_artifcat_name'
        run: |
          find . -name "*.tgz"
          echo "ARTIFACT_NAME=$(find . -name "*.tgz" -maxdepth 1)" >> $GITHUB_ENV

      - name: 'helm:package:upload'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username kilnfi --password-stdin
          helm push ${{ env.ARTIFACT_NAME }} oci://${{ env.REGISTRY }}/kilnfi/helm-charts/
        env:
          REGISTRY: ghcr.io
